mod journal;
mod metadata;

use std::{
    io,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};
use sync_provider_core::{CiphertextDigest, ProviderError, RemoteRevision};
use thiserror::Error;
use uuid::Uuid;

use crate::store_io::{
    atomic_write, atomic_write_json, create_private_directory, read_private_file, remove_if_file,
    sync_directory,
};
use metadata::{MetadataKind, MetadataSchema};

const SCHEMA_VERSION: u32 = 2;
const MAX_METADATA_BYTES: u64 = 64 * 1024;
const BASE_METADATA: &str = "base.json";
const JOURNAL_METADATA: &str = "journal.json";

/// Collision-resistant random sync profile identity.
#[derive(Clone, Copy, Eq, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ProfileId(Uuid);

impl ProfileId {
    /// Generates a random UUID v4 profile identity.
    #[must_use]
    pub fn random() -> Self {
        Self(Uuid::new_v4())
    }

    /// Parses a UUID and rejects non-v4 identities.
    pub fn parse(value: &str) -> Result<Self, StoreError> {
        let value = Uuid::parse_str(value).map_err(|_| StoreError::InvalidMetadata)?;
        if value.get_version_num() != 4 {
            return Err(StoreError::InvalidMetadata);
        }
        Ok(Self(value))
    }

    /// Returns the canonical UUID string.
    #[must_use]
    pub fn to_canonical_string(self) -> String {
        self.0.hyphenated().to_string()
    }
}

/// Private stable identity binding a profile to one local source.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SourceBinding(String);

impl SourceBinding {
    /// Accepts a canonical lowercase SHA-256 binding generated by an adapter.
    pub fn from_sha256(value: String) -> Result<Self, StoreError> {
        CiphertextDigest::parse(value.clone()).map_err(|_| StoreError::InvalidMetadata)?;
        Ok(Self(value))
    }

    /// Returns the private canonical binding for profile metadata.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Private stable identity binding persisted sync state to one remote target.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TargetBinding(String);

impl TargetBinding {
    /// Accepts a canonical lowercase SHA-256 binding generated by an adapter.
    pub fn from_sha256(value: String) -> Result<Self, StoreError> {
        CiphertextDigest::parse(value.clone()).map_err(|_| StoreError::InvalidMetadata)?;
        Ok(Self(value))
    }

    /// Returns the private canonical target binding.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Startup-visible recovery state; checking it never performs network I/O.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RecoveryStatus {
    /// No active transaction exists.
    None,
    /// An authenticated user-triggered recovery must run before a new sync.
    Required,
    /// Target-unbound legacy or newer unsupported state requires explicit reset.
    Unsupported,
}

/// Private profile-scoped BASE and journal repository.
pub struct SyncStore {
    directory: PathBuf,
    profile_id: ProfileId,
    source: SourceBinding,
    target: TargetBinding,
}

impl SyncStore {
    /// Opens a profile directory beneath private per-user application data.
    pub fn open(
        application_data: impl AsRef<Path>,
        profile_id: ProfileId,
        source: SourceBinding,
        target: TargetBinding,
    ) -> Result<Self, StoreError> {
        let sync_root = application_data.as_ref().join("sync");
        let directory = sync_root.join(profile_id.to_canonical_string());
        create_private_directory(&sync_root)?;
        create_private_directory(&directory)?;
        Ok(Self {
            directory,
            profile_id,
            source,
            target,
        })
    }

    pub(crate) fn load_base(&self) -> Result<Option<BaseState>, StoreError> {
        let path = self.directory.join(BASE_METADATA);
        match self.metadata_schema(BASE_METADATA, MetadataKind::Base)? {
            MetadataSchema::Missing => return Ok(None),
            MetadataSchema::Unsupported => return Err(StoreError::UnsupportedSchema),
            MetadataSchema::Current => {}
        }
        let Some(metadata): Option<BaseMetadata> = self.read_metadata(&path, MetadataKind::Base)?
        else {
            return Ok(None);
        };
        self.validate_identity(metadata.profile_id, &metadata.source, &metadata.target)?;
        validate_private_filename(&metadata.ciphertext_file, "base-")?;
        let ciphertext = read_private_file(&self.directory.join(&metadata.ciphertext_file))?;
        let digest = CiphertextDigest::of(&ciphertext);
        if digest != metadata.ciphertext_sha256 {
            return Err(StoreError::CorruptBase);
        }
        Ok(Some(BaseState {
            ciphertext,
            digest,
            _remote_revision: metadata.remote_revision,
        }))
    }

    pub(crate) fn write_base(
        &self,
        ciphertext: &[u8],
        remote_revision: RemoteRevision,
    ) -> Result<(), StoreError> {
        let operation = Uuid::new_v4();
        let ciphertext_file = format!("base-{operation}.kdbx");
        let ciphertext_path = self.directory.join(&ciphertext_file);
        atomic_write(&ciphertext_path, ciphertext)?;
        let metadata = BaseMetadata {
            schema_version: SCHEMA_VERSION,
            profile_id: self.profile_id,
            source: self.source.clone(),
            target: self.target.clone(),
            ciphertext_file,
            ciphertext_sha256: CiphertextDigest::of(ciphertext),
            remote_revision,
        };
        let metadata_path = self.directory.join(BASE_METADATA);
        let old = self.read_metadata::<BaseMetadata>(&metadata_path, MetadataKind::Base)?;
        atomic_write_json(&metadata_path, &metadata)?;
        if let Some(old) = old
            && old.ciphertext_file != metadata.ciphertext_file
            && validate_private_filename(&old.ciphertext_file, "base-").is_ok()
        {
            remove_if_file(&self.directory.join(old.ciphertext_file))?;
        }
        sync_directory(&self.directory)
    }

    fn validate_identity(
        &self,
        profile_id: ProfileId,
        source: &SourceBinding,
        target: &TargetBinding,
    ) -> Result<(), StoreError> {
        if profile_id != self.profile_id {
            return Err(StoreError::WrongProfile);
        }
        if source != &self.source {
            return Err(StoreError::WrongSource);
        }
        if target != &self.target {
            return Err(StoreError::WrongTarget);
        }
        Ok(())
    }
}

pub(crate) struct BaseState {
    pub ciphertext: Vec<u8>,
    pub digest: CiphertextDigest,
    pub _remote_revision: RemoteRevision,
}

pub(crate) struct LoadedJournal {
    pub record: JournalRecord,
    pub candidate: Vec<u8>,
}

#[derive(Serialize, Deserialize)]
struct BaseMetadata {
    schema_version: u32,
    profile_id: ProfileId,
    source: SourceBinding,
    target: TargetBinding,
    ciphertext_file: String,
    ciphertext_sha256: CiphertextDigest,
    remote_revision: RemoteRevision,
}

#[derive(Clone, Copy, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) enum JournalPhase {
    Prepared,
    RemoteCommitted,
    LocalCommitted,
}

#[derive(Serialize, Deserialize)]
pub(crate) struct JournalRecord {
    schema_version: u32,
    profile_id: ProfileId,
    pub source: SourceBinding,
    target: TargetBinding,
    pub operation_id: Uuid,
    pub phase: JournalPhase,
    pub expected_local_sha256: CiphertextDigest,
    pub expected_remote_revision: Option<RemoteRevision>,
    candidate_file: String,
    pub candidate_sha256: CiphertextDigest,
    pub committed_remote_revision: Option<RemoteRevision>,
}

/// Private persistence failure. No path is included in display text.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum StoreError {
    #[error("synchronization metadata could not be read or written")]
    Io(#[source] io::Error),
    #[error("synchronization metadata is invalid")]
    InvalidMetadata,
    #[error("the synchronized base is corrupt")]
    CorruptBase,
    #[error("the synchronization journal is corrupt")]
    CorruptJournal,
    #[error("the synchronization metadata schema is unsupported")]
    UnsupportedSchema,
    #[error("synchronization metadata belongs to another profile")]
    WrongProfile,
    #[error("the synchronization profile belongs to another local vault")]
    WrongSource,
    #[error("synchronization metadata belongs to another remote target")]
    WrongTarget,
    #[error("synchronization recovery is already required")]
    ActiveJournal,
}

impl From<ProviderError> for StoreError {
    fn from(_: ProviderError) -> Self {
        Self::InvalidMetadata
    }
}

fn validate_private_filename(value: &str, prefix: &str) -> Result<(), StoreError> {
    let path = Path::new(value);
    if path.components().count() == 1
        && value.starts_with(prefix)
        && (value.ends_with(".kdbx") || value.ends_with(".json"))
    {
        Ok(())
    } else {
        Err(StoreError::InvalidMetadata)
    }
}
